// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetShopAPI.Data;

#nullable disable

namespace PetShopAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260326031539_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("PetShopAPI.Models.Atendimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int?>("FuncionarioId")
                        .HasColumnType("int");

                    b.Property<int>("PetId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("entrada")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("id_cliente")
                        .HasColumnType("int");

                    b.Property<int?>("id_funcionario_entrada")
                        .HasColumnType("int");

                    b.Property<int?>("id_funcionario_saida")
                        .HasColumnType("int");

                    b.Property<int>("id_pet")
                        .HasColumnType("int");

                    b.Property<DateTime?>("saida")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("FuncionarioId");

                    b.HasIndex("PetId");

                    b.ToTable("Atendimento");
                });

            modelBuilder.Entity("PetShopAPI.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("bairro")
                        .HasColumnType("longtext");

                    b.Property<string>("cidade")
                        .HasColumnType("longtext");

                    b.Property<string>("cpf")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("datanascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("endereco")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("numero")
                        .HasColumnType("int");

                    b.Property<string>("telefone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("PetShopAPI.Models.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("bairro")
                        .HasColumnType("longtext");

                    b.Property<string>("cargo")
                        .HasColumnType("longtext");

                    b.Property<string>("cidade")
                        .HasColumnType("longtext");

                    b.Property<string>("cpf")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("dataAdmissao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("dataDemissao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("dataNascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("email")
                        .HasColumnType("longtext");

                    b.Property<string>("endereco")
                        .HasColumnType("longtext");

                    b.Property<string>("funcao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("numero")
                        .HasColumnType("int");

                    b.Property<string>("telefone")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Funcionario");
                });

            modelBuilder.Entity("PetShopAPI.Models.Orcamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AtendimentoId")
                        .HasColumnType("int");

                    b.Property<int>("id_atendimento")
                        .HasColumnType("int");

                    b.Property<string>("tipo_pagamneto")
                        .HasColumnType("longtext");

                    b.Property<double>("valor")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("AtendimentoId");

                    b.ToTable("Orcamento");
                });

            modelBuilder.Entity("PetShopAPI.Models.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int>("Pet_RacaId")
                        .HasColumnType("int");

                    b.Property<int>("Pet_TipoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("datanascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("especie")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("id_pet_raca")
                        .HasColumnType("int");

                    b.Property<int>("id_pet_tipo")
                        .HasColumnType("int");

                    b.Property<string>("nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("peso")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("raca")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("Pet_RacaId");

                    b.HasIndex("Pet_TipoId");

                    b.ToTable("Pet");
                });

            modelBuilder.Entity("PetShopAPI.Models.PetCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int>("Id_cliente")
                        .HasColumnType("int");

                    b.Property<int>("Id_pet")
                        .HasColumnType("int");

                    b.Property<int>("PetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("PetId");

                    b.ToTable("PetCliente");
                });

            modelBuilder.Entity("PetShopAPI.Models.Pet_Raca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Pet_Raca");
                });

            modelBuilder.Entity("PetShopAPI.Models.Pet_Tipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("descriacao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Pet_Tipo");
                });

            modelBuilder.Entity("PetShopAPI.Models.Servicos_Banho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Servicos_Banho");
                });

            modelBuilder.Entity("PetShopAPI.Models.Atendimento", b =>
                {
                    b.HasOne("PetShopAPI.Models.Cliente", "Cliente")
                        .WithMany("Atendimento")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetShopAPI.Models.Funcionario", null)
                        .WithMany("Atendimento")
                        .HasForeignKey("FuncionarioId");

                    b.HasOne("PetShopAPI.Models.Pet", "Pet")
                        .WithMany("Atendimento")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetShopAPI.Models.Orcamento", b =>
                {
                    b.HasOne("PetShopAPI.Models.Atendimento", "Atendimento")
                        .WithMany("Orcamento")
                        .HasForeignKey("AtendimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atendimento");
                });

            modelBuilder.Entity("PetShopAPI.Models.Pet", b =>
                {
                    b.HasOne("PetShopAPI.Models.Cliente", null)
                        .WithMany("Pet")
                        .HasForeignKey("ClienteId");

                    b.HasOne("PetShopAPI.Models.Pet_Raca", "Pet_Raca")
                        .WithMany("Pet")
                        .HasForeignKey("Pet_RacaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetShopAPI.Models.Pet_Tipo", "Pet_Tipo")
                        .WithMany("Pet")
                        .HasForeignKey("Pet_TipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet_Raca");

                    b.Navigation("Pet_Tipo");
                });

            modelBuilder.Entity("PetShopAPI.Models.PetCliente", b =>
                {
                    b.HasOne("PetShopAPI.Models.Cliente", "Cliente")
                        .WithMany("PetCliente")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetShopAPI.Models.Pet", "Pet")
                        .WithMany("PetCliente")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetShopAPI.Models.Atendimento", b =>
                {
                    b.Navigation("Orcamento");
                });

            modelBuilder.Entity("PetShopAPI.Models.Cliente", b =>
                {
                    b.Navigation("Atendimento");

                    b.Navigation("Pet");

                    b.Navigation("PetCliente");
                });

            modelBuilder.Entity("PetShopAPI.Models.Funcionario", b =>
                {
                    b.Navigation("Atendimento");
                });

            modelBuilder.Entity("PetShopAPI.Models.Pet", b =>
                {
                    b.Navigation("Atendimento");

                    b.Navigation("PetCliente");
                });

            modelBuilder.Entity("PetShopAPI.Models.Pet_Raca", b =>
                {
                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetShopAPI.Models.Pet_Tipo", b =>
                {
                    b.Navigation("Pet");
                });
#pragma warning restore 612, 618
        }
    }
}
